repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: ruff check --fix
        language: system
        types: [python]
        
      - id: ruff-format
        name: ruff format
        entry: ruff format
        language: system
        types: [python]
        
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        args: [--line-length=100]
        
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [python]
        args: [--profile=black, --line-length=100]