# Video Transformer Model Configuration
# Attention-based model for video understanding

name: video_transformer
description: "Video Transformer for temporal modeling"
seed: 42

layers:
  - type: video_transformer
    input_channels: 3
    hidden_dim: 512
    num_layers: 6
    num_heads: 8
    input_height: 224
    input_width: 224
    sequence_length: 16
    num_classes: 1000
    dropout: 0.1
