apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: adaptive-nn-prod
    component: adaptive-neural-network
  name: adaptive-nn-prod
  namespace: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: adaptive-nn-prod
  template:
    metadata:
      labels:
        app: adaptive-nn-prod
    spec:
      containers:
      - env:
        - name: MODEL_PATH
          value: /models
        - name: PORT
          value: '8080'
        image: adaptiveneuralnetwork:latest
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        name: adaptive-nn
        ports:
        - containerPort: 8080
          name: http
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          limits:
            cpu: '2'
            memory: 4Gi
            nvidia.com/gpu: '1'
          requests:
            cpu: 500m
            memory: 1Gi
            nvidia.com/gpu: '1'
        volumeMounts:
        - mountPath: /models
          name: model-storage
      volumes:
      - name: model-storage
        persistentVolumeClaim:
          claimName: adaptive-nn-prod-models
