apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adaptive-nn-prod-models
  namespace: production
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: default
