apiVersion: v1
kind: Service
metadata:
  labels:
    app: adaptive-nn-prod
  name: adaptive-nn-prod-service
  namespace: production
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: adaptive-nn-prod
  type: ClusterIP
