api_endpoints:
  ai: https://example.com/ai_signal
  human: https://example.com/human_signal
  world: https://example.com/world_signal
external_signal_interval: 5
nodes: 3
spatial_dims: 2
topology: grid
