# 2D Network Configuration Example
# Traditional planar network suitable for most applications
# Provides good performance and easy visualization

spatial_dims: 2
nodes: 9
topology: grid

# Standard 2D settings
external_signal_interval: 5

# API endpoints for external signals (optional)
api_endpoints:
  human: null
  ai: null
  world: null

# Network parameters optimized for 2D
communication_range: 2.0
collision_radius: 0.5

# Performance settings
max_nodes_per_step: 100
simulation_speed: 1.0

# Logging and monitoring
log_level: "INFO"
metrics_enabled: true